Survey/Pages/SurveyPages/AnswerCreator.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Survey.Data;
using Survey.Domain;

namespace Survey
{
    public class AnswerCreatorModel : PageModel
    {
        private readonly IHtmlHelper _htmlHelper;
        private readonly ISurveyRepository _surveyRepository;
        private readonly ILogger<AnswerCreatorModel> _logger;

        public IEnumerable<SelectListItem> AnswerType { get; set; }

        [BindProperty]
        public Answer Answer { get; set; }
        public AnswerCreatorModel(IHtmlHelper htmlHelper, ISurveyRepository surveyRepository, ILogger<AnswerCreatorModel> logger )
        {
            _htmlHelper = htmlHelper;
            _surveyRepository = surveyRepository;
            _logger = logger;
        }
        public IActionResult OnGet(int? IdQuestion)
        {
            _logger.LogInformation($"Get AnswerCreator for Question {IdQuestion}");

            AnswerType = _htmlHelper.GetEnumSelectList<AnswerType>();
            if (!IdQuestion.HasValue)
            {
                return RedirectToPage("./NotFound", new { IdQuestion = IdQuestion });
            }
            return Page();

        }
        public async Task<IActionResult> OnPost(Answer answer, int IdQuestion)
        {
            _logger.LogInformation($"OnPost AnswerCreator for Question {IdQuestion} with AnswerName : {answer.AnswerName}");

            _surveyRepository.AddAnswerbyQuestion(answer, IdQuestion);
            await _surveyRepository.Commit();
            return RedirectToPage("./QuestionCreator", new { IdQuestion = answer.IdQuestion });
        }
        public IActionResult OnPostQuestionCreator(int? IdQuestion)
        {
            _logger.LogInformation("OnPostQuestionCreator");

            return RedirectToPage("./QuestionCreator", new { IdQuestion = IdQuestion });
        }


    }
}

Survey/Pages/SurveyPages/DeleteAnswer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Survey.Data;
using Survey.Domain;

namespace Survey
{
    public class DeleteAnswerModel : PageModel
    {
        private readonly ISurveyRepository _surveyRepository;
        private readonly ILogger<DeleteAnswerModel> _logger;

        [BindProperty]
        public Answer Answer { get; set; }
       
        public DeleteAnswerModel(ISurveyRepository surveyRepository, ILogger<DeleteAnswerModel> logger)
        {
            _surveyRepository = surveyRepository;
            _logger = logger;
        }
        public async Task<IActionResult> OnGet(int idAnswer)
        {
            _logger.LogInformation($"Prepering to delete AnswerID {idAnswer}");

            Answer = await  _surveyRepository.GetAnswerByID(idAnswer);

            return Page();

        }

        public async Task<IActionResult> OnPost(int idAnswer)
        {
            Answer = await _surveyRepository.GetAnswerByID(idAnswer);

            _logger.LogInformation($"Deleting AnswerID {Answer.Id}");


            await _surveyRepository.DeleteAnswer(Answer.Id);
            await _surveyRepository.Commit();

             _logger.LogInformation($"Deleted AnswerID {Answer.Id}");

            return RedirectToPage("./QuestionCreator", new { IdQuestion = Answer.IdQuestion });

        }
    }
}

Survey/Pages/SurveyPages/NotFound.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Survey
{
    public class NotFoundModel : PageModel
    {
        private readonly ILogger<NotFoundModel> _logger;

        public NotFoundModel(ILogger<NotFoundModel> logger)
        {
            _logger = logger;
        }
        public void OnGet(int? IdQuestion)
        {
           _logger.LogWarning($"Get NotFound for QUestion ID : {IdQuestion}");
        }
    }
}

Survey/Pages/SurveyPages/QuestionCreator.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Survey.Data;
using Survey.Domain;

namespace Survey
{
    public class QuestionCreatorModel : PageModel
    {
        private readonly IHtmlHelper _htmlHelper;
        private readonly ISurveyRepository _surveyRepository;
        private readonly ILogger<QuestionCreatorModel> _logger;

        public IEnumerable<SelectListItem> QuestionType { get; set; }
        public IEnumerable<SelectListItem> AnswerType { get; set; }

        [BindProperty]
        public Question Question { get; set; }
        //public IEnumerable<Answer> Answers { get; set; }
        public QuestionCreatorModel(IHtmlHelper htmlHelper, ISurveyRepository surveyRepository, ILogger<QuestionCreatorModel> logger)
        {
            _htmlHelper = htmlHelper;
            _surveyRepository = surveyRepository;
            _logger = logger;
        }
        public async  Task<IActionResult> OnGet(int? IdQuestion)
        {
            _logger.LogInformation($"Geting Question Page for {IdQuestion}");

            QuestionType = _htmlHelper.GetEnumSelectList<QuestionType>();
            AnswerType = _htmlHelper.GetEnumSelectList<AnswerType>();
            if (IdQuestion.HasValue)
            {
                Question = await _surveyRepository.GetQuestionbyID(IdQuestion.Value);
                Question.Answers = await _surveyRepository.GetAnswersbyQuestion(IdQuestion.Value);
            }
            else
            {
                Question = new Question();
                Question.Answers = new List<Answer>();

            }
            if (Question == null)
            {
                return  RedirectToPage("./NotFound", new { IdQuestion = IdQuestion });
            }
            return  Page();
        }
        public async Task<IActionResult> OnPostAnswerCreator()
        {
            _logger.LogInformation($"OnPostAnswerCreator for QuesitionName : {Question.QuestionName}");

            if (Question.IdQuestion == 0)
            {
                 _surveyRepository.AddQuestion(Question);
                await _surveyRepository.Commit();
            }
          
            return  RedirectToPage("./AnswerCreator", new { IdQuestion = Question.IdQuestion });
        }

        public IActionResult OnPostQuestionCreator()
        {
            _logger.LogInformation("OnPostQuestionCreator");

            return RedirectToPage("./QuestionCreator");
        }

        public IActionResult OnPostSave()
        {
            _logger.LogInformation("OnPostSave");

            return RedirectToPage("./Save", new { IdQuestion = Question.IdQuestion });
        }
        

    }
}

Survey/Pages/SurveyPages/ResultChart.cshtml.cs
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using FusionCharts.DataEngine;
using FusionCharts.Visualization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Survey.Data;
using Survey.Domain;

namespace Survey
{
    public class ResultChartModel : PageModel
    {
        private readonly ISurveyRepository _surveyRepository;
        private readonly ILogger<ResultChartModel> _logger;

        public ResultChartModel(ISurveyRepository surveyRepository, ILogger<ResultChartModel> logger)
        {
            _surveyRepository = surveyRepository;
            _logger = logger;
        }

        [TempData]
        public string Message { get; set; }

        public string ChartJson { get; internal set; }
        public async Task<ActionResult> OnGet(int IdQuestion)
        {
            _logger.LogInformation($"Get Chart for Question id : {IdQuestion}");

            var selectedAnswers = await _surveyRepository.GetSelectedAnswers(IdQuestion);
            var selectedQuestion = await _surveyRepository.GetQuestionbyID(IdQuestion);

            DataTable ChartData = new DataTable();

            ChartData.Columns.Add("Answers", typeof(string));
            ChartData.Columns.Add("Votes", typeof(int));

            var distinctedAnswers = selectedAnswers.GroupBy(x => x.AnswerName).Select(x => x.FirstOrDefault());

            foreach (Answer answer in distinctedAnswers)
            {
                if(answer.AnswerType == AnswerType.Open)
                {
                    ChartData.Rows.Add("Others", selectedAnswers.Where(a => a.AnswerType == AnswerType.Open).Count());
                }
                else
      
                {
                    ChartData.Rows.Add(answer.AnswerName, selectedAnswers.Where(a => a.AnswerName == answer.AnswerName).Count());
                }
            }

            StaticSource source = new StaticSource(ChartData);

            DataModel model = new DataModel();
            model.DataSources.Add(source);
            Charts.ColumnChart column = new Charts.ColumnChart("first_chart");

            column.Width.Pixel(700);
            column.Height.Pixel(400);
            column.Data.Source = model;
            column.Caption.Text = selectedQuestion.QuestionName;
            column.SubCaption.Text = "Results";
            column.Legend.Show = false;
            column.XAxis.Text = "Answers";
            column.YAxis.Text = "Votes";
            column.ThemeName = FusionChartsTheme.ThemeName.FUSION;

            ChartJson = column.Render();
            return Page();
        }
        public  IActionResult OnPostIndex()
        {
            return RedirectToPage("/Index");
        }
    }
}



   

Survey/Pages/SurveyPages/Save.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Survey.Data;
using Survey.Domain;

namespace Survey
{
    public class SaveModel : PageModel
    {
        private readonly IHtmlHelper _htmlHelper;
        private readonly ISurveyRepository _surveyRepository;
        private readonly ILogger<SaveModel> _logger;

        [BindProperty]
        public Question Question { get; set; }
        public Answer Answer { get; set; }

        public SaveModel(IHtmlHelper htmlHelper, ISurveyRepository surveyRepository, ILogger<SaveModel> logger)
        {
            _htmlHelper = htmlHelper;
            _surveyRepository = surveyRepository;
            _logger = logger;
        }

        public async Task<IActionResult> OnGet(int IdQuestion)
        {
            _logger.LogInformation($"Get SavePage for id Question : {IdQuestion}");

            Question = await _surveyRepository.GetQuestionbyID(IdQuestion);
            Question.Answers = await _surveyRepository.GetAnswersbyQuestion(IdQuestion);
            return Page();
        }

        public async Task<IActionResult> OnPostVote()
        {
            _logger.LogInformation($"Post Save for id Question : {Question.IdQuestion}");

            if (Question.QuestionType == QuestionType.Single)
            {
                Answer = await _surveyRepository.GetAnswerByID(Question.SelectedAnswersId.GetValueOrDefault());
                Answer.Selected = true;
                _surveyRepository.AddAnswerbyQuestion(Answer, Answer.IdQuestion);
                await _surveyRepository.Commit();
            }
            else
            {
                foreach (var answer in Question.Answers)
                {
                    if(answer.Selected)
                    {
                        Answer = await _surveyRepository.GetAnswerByID(answer.Id);
                        Answer.Selected = true;
                        _surveyRepository.AddAnswerbyQuestion(Answer, Answer.IdQuestion);
                        await _surveyRepository.Commit();
                    }
                }
            }
            TempData["Message"] = $"You voted for {Answer.AnswerName} !";
            return RedirectToPage("./ResultChart", new { IdQuestion = Answer.IdQuestion });
        }

           

    }
}

Survey/Pages/SurveyPages/AnswerCreator.cshtml
@page  "{IdQuestion:int}"
@model Survey.AnswerCreatorModel
@{
    ViewData["Title"] = "AnswerCreator";
}

<h1>AnswerCreator</h1>

<form method="post">

    <input type="hidden" asp-for="Answer.Id" />
    <div class="form-group">
        <label asp-for="Answer.AnswerName"></label>
        <input asp-for="Answer.AnswerName" class="form-control" />
        <span class="text-danger" asp-validation-for="Answer.AnswerName"></span>
    </div>
    <div class="form-group">
        <label asp-for="Answer.AnswerType"></label>
        <select class="form-control" asp-for="Answer.AnswerType"
                asp-items="Model.AnswerType"></select>
        <span class="text-danger" asp-validation-for="Answer.AnswerType"></span>
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
    <button type="submit" class="btn btn-secondary ml-1" asp-page-handler="QuestionCreator">Cancel</button>

</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Survey/Pages/SurveyPages/DeleteAnswer.cshtml
@page "{idAnswer:int?}"
@model Survey.DeleteAnswerModel
@{
    ViewData["Title"] = "DeleteAnswer";
}

<h1>DeleteAnswer</h1>

<h2>Delete!</h2>
<div class="alert alert-danger">
    Are you sure you want to delete @Model.Answer.AnswerName ?
</div>
<form method="post">
    <input type="hidden" asp-for=@Model.Answer.Id />
    <button type="submit" class="btn btn-danger">Yes!</button>

    <a asp-page="QuestionCreator" asp-route-IdQuestion=@Model.Answer.IdQuestion class="btn btn-default">Cancel</a>
</form>

Survey/Pages/SurveyPages/NotFound.cshtml
@page "{IdQuestion:int?}"


@{
    ViewData["Title"] = "NotFound";
}

<h2>Your Question was not found</h2>
<a asp-page="./QuestionCreator" class="btn btn-primary">Crete one !</a>

Survey/Pages/SurveyPages/QuestionCreator.cshtml
@page "{IdQuestion:int?}"
@model Survey.QuestionCreatorModel
@{
    ViewData["Title"] = "QuestionCreator";
}

<h1>QuestionCreator</h1>
<form method="post">

    <input type="hidden" asp-for="Question.IdQuestion" />

    <div class="form-group">
        <label asp-for="Question.QuestionName"></label>
        @if (Model.Question.IdQuestion != 0)
        {
            <input asp-for="Question.QuestionName" class="form-control" disabled />
        }
        else
        {
            <input asp-for="Question.QuestionName" class="form-control" />
        }
        <span class="text-danger" asp-validation-for="Question.QuestionName"></span>
    </div>

    <div class="form-group">
        <label asp-for="Question.QuestionType"></label>
        @if (Model.Question.IdQuestion != 0)
        {
            <select class="form-control" asp-for="Question.QuestionType"
                    asp-items="Model.QuestionType" disabled></select>
        }
        else
        {
            <select class="form-control" asp-for="Question.QuestionType"
                    asp-items="Model.QuestionType"></select>
        }
        <span class="text-danger" asp-validation-for="Question.QuestionType"></span>
    </div>


    @if (Model.Question.Answers.Count() >= 1)
    {
        <div class="form-group  mt-5 ml-5">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">AnswerName</th>
                        <th scope="col">AnswerType</th>
                        <th scope="col">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Question.Answers.Count(); i++)
                    {
                    <tr>
                        <td>@Model.Question.Answers[i].AnswerName</td>
                        <td>@Model.Question.Answers[i].AnswerType.ToString()</td>
                        <td>
                            <a class="btn btn-info" asp-page="DeleteAnswer" asp-route-idAnswer=@Model.Question.Answers[i].Id>
                                Delete! 
                            </a>
                        </td>

                    </tr>
                    }
                </tbody>
            </table>
            <script>
                var tables = document.getElementsByTagName('table');
                var table = tables[tables.length - 1];
                var rows = table.rows;
                for (var i = 1, td; i < rows.length; i++) {
                    td = document.createElement('td');
                    td.appendChild(document.createTextNode(i));
                    rows[i].insertBefore(td, rows[i].firstChild);
                }
            </script>
        </div>
    }
    <div class="form-group">
        <div class="row nav-row">
            <button type="submit" class="btn btn-primary mr-1" asp-page-handler="AnswerCreator" >Add Answers to Question</button>
            <button type="submit" class="btn btn-secondary ml-1" asp-page-handler="QuestionCreator">Cancel</button>
        </div>

        <div class="row nav-row">
            <button type="submit" class="btn btn-success mt-3" asp-page-handler="Save">Save</button>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Survey/Pages/SurveyPages/ResultChart.cshtml
@page  "{IdQuestion:int}"

@model Survey.ResultChartModel


    <head>
        <meta name="viewport" content="width=device-width" />
        <script src="//cdn.fusioncharts.com/fusioncharts/latest/fusioncharts.js"></script>
        <script src="//cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.fusion.js"></script>
        <title>ColumnChart</title>
    </head>

    <body>
        <form method="post">
            <div>@Html.Raw(Model.ChartJson)</div>





            @if (Model.Message != null)
            {
                <div class="alert alert-info" role="alert">@Model.Message</div>
            }
            <button type="submit" class="btn btn-secondary" asp-page-handler="Index">Back to Main Menu</button>
        </form>
    </body>

Survey/Pages/SurveyPages/Save.cshtml
@page "{IdQuestion:int?}"
@model Survey.SaveModel
@{
    ViewData["Title"] = "Save";
}

<form method="post">

    <h3>@Model.Question.QuestionName</h3>
    @if (@Model.Question.QuestionType == Domain.QuestionType.Multi)
    {
        @for (int i = 0; i < Model.Question.Answers.Count(); i++)

        {
            @if (Model.Question.Answers[i].AnswerType == Domain.AnswerType.Closed)
            {
                <div class="checkbox">
                    <input type="checkbox" asp-for=@Model.Question.Answers[i].Selected />
                    <label>@Model.Question.Answers[i].AnswerName</label>
                    <input type="hidden" asp-for=@Model.Question.Answers[i].Id />
                    <input type="hidden" asp-for=@Model.Question.QuestionType />
                </div>
            }
            else
            {
                <div class="checkbox">
                    <input type="checkbox" asp-for=@Model.Question.Answers[i].Selected />
                    <input asp-for="@Model.Question.Answers[i].AnswerName" />
                    <input type="hidden" asp-for=@Model.Question.Answers[i].Id />
                    <input type="hidden" asp-for=@Model.Question.QuestionType />
                </div>
            }
        }
    }


    @if (@Model.Question.QuestionType == Domain.QuestionType.Single)
    {
        @for (int i = 0; i < Model.Question.Answers.Count(); i++)
        {
            @if (Model.Question.Answers[i].AnswerType == Domain.AnswerType.Closed)
            {
                <div class="radio">
                    @Html.RadioButtonFor(m => m.Question.SelectedAnswersId, Model.Question.Answers[i].Id)
                    <input type="hidden" asp-for=@Model.Question.QuestionType />
                    <label>@Model.Question.Answers[i].AnswerName</label>
                </div>
            }
            else
            {
                <div class="radio">
                    @Html.RadioButtonFor(m => m.Question.SelectedAnswersId, Model.Question.Answers[i].Id)
                    <input type="hidden" asp-for=@Model.Question.QuestionType />
                    <input asp-for="@Model.Question.Answers[i].AnswerName" />
                </div>
            }
        }
    }

    <button type="submit" class="btn btn-success mt-3" asp-page-handler="Vote">Vote !</button>
</form>